"""init

Revision ID: 9ced04691b62
Revises:
Create Date: 2025-02-14 19:32:09.795153

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ced04691b62"
down_revision = None
branch_labels = None
depends_on = None


def create_primary_language():
    op.execute(
        "INSERT INTO languages (emoji, code, is_primary) VALUES ('🇺🇸', 'en', true), ('🇷🇺', 'ru', false)",
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("status", sa.VARCHAR(length=255), server_default="active", nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_articles_status"), "articles", ["status"], unique=False)
    op.create_table(
        "languages",
        sa.Column("emoji", sa.VARCHAR(length=255), nullable=False),
        sa.Column("code", sa.VARCHAR(length=255), nullable=False),
        sa.Column("is_primary", sa.BOOLEAN(), server_default="f", nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_languages_code"), "languages", ["code"], unique=True)
    op.create_index(op.f("ix_languages_is_primary"), "languages", ["is_primary"], unique=False)
    op.create_table(
        "article_medias",
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=255), nullable=False),
        sa.Column("article_id", sa.BIGINT(), nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "language_id"),
    )
    op.create_index(op.f("ix_article_medias_article_id"), "article_medias", ["article_id"], unique=False)
    op.create_index(op.f("ix_article_medias_content_type"), "article_medias", ["content_type"], unique=False)
    op.create_index(op.f("ix_article_medias_language_id"), "article_medias", ["language_id"], unique=False)
    op.create_table(
        "article_texts",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("md_content", sa.Text(), nullable=False),
        sa.Column("article_id", sa.BIGINT(), nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "language_id"),
    )
    op.create_index(op.f("ix_article_texts_article_id"), "article_texts", ["article_id"], unique=False)
    op.create_index(op.f("ix_article_texts_language_id"), "article_texts", ["language_id"], unique=False)
    op.create_table(
        "article_titles",
        sa.Column("content", sa.VARCHAR(length=255), nullable=False),
        sa.Column("md_content", sa.Text(), nullable=False),
        sa.Column("article_id", sa.BIGINT(), nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "language_id"),
    )
    op.create_index(op.f("ix_article_titles_article_id"), "article_titles", ["article_id"], unique=False)
    op.create_index(op.f("ix_article_titles_content"), "article_titles", ["content"], unique=False)
    op.create_index(op.f("ix_article_titles_language_id"), "article_titles", ["language_id"], unique=False)
    op.create_table(
        "main_articles",
        sa.Column("order_by", sa.SMALLINT(), nullable=False),
        sa.Column("article_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("username", sa.VARCHAR(length=255), nullable=True),
        sa.Column("mention", sa.VARCHAR(length=255), nullable=True),
        sa.Column("full_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("role", sa.VARCHAR(length=255), server_default="default", nullable=True),
        sa.Column("language_id", sa.BIGINT(), nullable=True),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "drafts",
        sa.Column("redactor_id", sa.BIGINT(), nullable=False),
        sa.Column("status", sa.VARCHAR(length=255), server_default="created", nullable=False),
        sa.Column("origin_article_id", sa.BIGINT(), nullable=True),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["origin_article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["redactor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drafts_redactor_id"), "drafts", ["redactor_id"], unique=False)
    op.create_index(op.f("ix_drafts_status"), "drafts", ["status"], unique=False)
    op.create_table(
        "reports",
        sa.Column("message", sa.VARCHAR(length=255), nullable=True),
        sa.Column("status", sa.VARCHAR(length=255), server_default="created", nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("reporter_id", sa.BIGINT(), nullable=False),
        sa.Column("article_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_article_id"), "reports", ["article_id"], unique=False)
    op.create_index(op.f("ix_reports_language_id"), "reports", ["language_id"], unique=False)
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_table(
        "changelogs",
        sa.Column("redactor_id", sa.BIGINT(), nullable=False),
        sa.Column("article_id", sa.BIGINT(), nullable=False),
        sa.Column("draft_id", sa.BIGINT(), nullable=False),
        sa.Column("old_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["redactor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_changelogs_article_id"), "changelogs", ["article_id"], unique=False)
    op.create_table(
        "draft_medias",
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.VARCHAR(length=255), nullable=False),
        sa.Column("draft_id", sa.BIGINT(), nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "language_id"),
    )
    op.create_index(op.f("ix_draft_medias_content_type"), "draft_medias", ["content_type"], unique=False)
    op.create_index(op.f("ix_draft_medias_draft_id"), "draft_medias", ["draft_id"], unique=False)
    op.create_index(op.f("ix_draft_medias_language_id"), "draft_medias", ["language_id"], unique=False)
    op.create_table(
        "draft_texts",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("md_content", sa.Text(), nullable=False),
        sa.Column("draft_id", sa.BIGINT(), nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "language_id"),
    )
    op.create_index(op.f("ix_draft_texts_draft_id"), "draft_texts", ["draft_id"], unique=False)
    op.create_index(op.f("ix_draft_texts_language_id"), "draft_texts", ["language_id"], unique=False)
    op.create_table(
        "draft_titles",
        sa.Column("content", sa.VARCHAR(length=255), nullable=False),
        sa.Column("md_content", sa.Text(), nullable=False),
        sa.Column("draft_id", sa.BIGINT(), nullable=False),
        sa.Column("language_id", sa.BIGINT(), nullable=False),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "language_id"),
    )
    op.create_index(op.f("ix_draft_titles_content"), "draft_titles", ["content"], unique=False)
    op.create_index(op.f("ix_draft_titles_draft_id"), "draft_titles", ["draft_id"], unique=False)
    op.create_index(op.f("ix_draft_titles_language_id"), "draft_titles", ["language_id"], unique=False)
    # ### end Alembic commands ###

    create_primary_language()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_draft_titles_language_id"), table_name="draft_titles")
    op.drop_index(op.f("ix_draft_titles_draft_id"), table_name="draft_titles")
    op.drop_index(op.f("ix_draft_titles_content"), table_name="draft_titles")
    op.drop_table("draft_titles")
    op.drop_index(op.f("ix_draft_texts_language_id"), table_name="draft_texts")
    op.drop_index(op.f("ix_draft_texts_draft_id"), table_name="draft_texts")
    op.drop_table("draft_texts")
    op.drop_index(op.f("ix_draft_medias_language_id"), table_name="draft_medias")
    op.drop_index(op.f("ix_draft_medias_draft_id"), table_name="draft_medias")
    op.drop_index(op.f("ix_draft_medias_content_type"), table_name="draft_medias")
    op.drop_table("draft_medias")
    op.drop_index(op.f("ix_changelogs_article_id"), table_name="changelogs")
    op.drop_table("changelogs")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_language_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_article_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_drafts_status"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_redactor_id"), table_name="drafts")
    op.drop_table("drafts")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("main_articles")
    op.drop_index(op.f("ix_article_titles_language_id"), table_name="article_titles")
    op.drop_index(op.f("ix_article_titles_content"), table_name="article_titles")
    op.drop_index(op.f("ix_article_titles_article_id"), table_name="article_titles")
    op.drop_table("article_titles")
    op.drop_index(op.f("ix_article_texts_language_id"), table_name="article_texts")
    op.drop_index(op.f("ix_article_texts_article_id"), table_name="article_texts")
    op.drop_table("article_texts")
    op.drop_index(op.f("ix_article_medias_language_id"), table_name="article_medias")
    op.drop_index(op.f("ix_article_medias_content_type"), table_name="article_medias")
    op.drop_index(op.f("ix_article_medias_article_id"), table_name="article_medias")
    op.drop_table("article_medias")
    op.drop_index(op.f("ix_languages_is_primary"), table_name="languages")
    op.drop_index(op.f("ix_languages_code"), table_name="languages")
    op.drop_table("languages")
    op.drop_index(op.f("ix_articles_status"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
