version: '3.3'

services:

  bot:
    build: .
    restart: on-failure
    command: python main.py
    depends_on:
      - redis
      - db
    environment:
      ENVIRONMENT: prod
      BOT_TOKEN: <bot-token>
      DATABASE_HOST: db
      DATABASE_USER: sample_tg_bot_app
      DATABASE_PASSWORD: sample_tg_bot_app
      DATABASE_NAME: sample_tg_bot_app
      REDIS_DSN: redis://redis:6379

  db:
    image: postgres:13.4
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: sample_tg_bot_app
      POSTGRES_PASSWORD: sample_tg_bot_app
      POSTGRES_DB: sample_tg_bot_app
      TZ: UTC
    healthcheck:
      test: pg_isready -U sample_tg_bot_app -d sample_tg_bot_app
      interval: 30s
      timeout: 3s
      retries: 3

  redis:
    image: redis:6.2.5
    restart: on-failure
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
